theme: 'readable'
title: 'Schafe sind bessere Rasenmäher'
pluralizelisttitles: False
enableRobotsTXT: true

params:
  author: 'Robert Lützner'
  mastodon: 'https://rollenspiel.social/@mforester'
  codeberg: 'https://codeberg.org/rluetzner'
  subtitle: '...ist einfach so!'
  dateFormat: '2. Jan 2006'
  # The following items are not (yet) supported, but I'd like to use them!
  favicon: "/images/favicon.ico"
  site_logo: "/images/schaf-rund.webp"
  mainSections:
    - posts
    - tech
    - stories

menu:
  main:
    - name: 'Stuff'
      url: '/posts/'
      weight: 10
    - name: 'Tech'
      url: '/tech/'
      weight: 20
    - name: 'Mindfulness'
      url: '/mindfulness/'
      weight: 30
    - name: 'Geschichten'
      url: '/stories/'
      weight: 90
    - name: 'Imprint'
      url: '/imprint/'
      weight: 99
