title = "Schafe sind bessere Rasenmäher"
baseURL = "https://www.schafe-sind-bessere-rasenmaeher.de"
languageCode = "en-US"
theme = ["ananke"]
# resourceDir = "../resources"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[menu]
[[menu.main]]
  identifier = 'Stuff'
  name = 'Stuff'
  title = 'Stuff'
  url = '/posts/'
  weight = -110

[[menu.main]]
  identifier = 'Tech'
  name = 'Tech'
  title = 'Tech'
  url = '/tech/'
  weight = -100

[[menu.main]]
  identifier = 'Geschichten'
  name = 'Geschichten'
  title = 'Geschichten'
  url = '/stories/'
  weight = -50

[[menu.main]]
  identifier = 'About'
  name = 'About'
  title = 'About'
  url = '/about/'
  weight = 110

[[menu.main]]
  identifier = 'Imprint'
  name = 'Imprint'
  title = 'Imprint'
  url = '/imprint/'
  weight = 150

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Robert Lützner"
  favicon = "images/favicon.ico"
  site_logo = "images/schaf-rund.png"
  description = "...ist einfach so!"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 3
  mainSections = ["posts", "tech", "stories"]
  show_reading_time = true
  date_format = "2. January 2006"

[[params.ananke_socials]]
name = "mastodon"
url = "https://rollenspiel.social/@mforester"

[[params.ananke_socials]]
name = "codeberg"
url = "https://codeberg.org/rluetzner"

[[params.ananke_socials]]
name = "gitlab"
url = "https://gitlab.com/rluetzner"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/rluetzner"

[[params.ananke_socials]]
name = "rss"
url = "https://schafe-sind-bessere-rasenmaeher.de/index.xml"
