name: update-robots-txt

on:
  schedule:
    # Every day at 3:29.
    - cron: '29 3 * * *'

jobs:
  update-robots-txt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update robots.txt
        run: .github/scripts/update-robots.sh
      - name: Create pull request if files have changed
        # https://github.com/marketplace/actions/create-pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          # First line is the commit subject as always. The rest goes
          # into the body.
          commit-message: |
            Update robots.txt from ai.robots.txt project

            See https://github.com/ai-robots-txt/ai.robots.txt
          branch: update-robots-txt
          delete-branch: true
          # Use 'GitHub' both times.
          # This is already the default for committer, but the author defaults
          # to the user who triggered the workflow run, which is the owner of
          # the repository.
          # We use the same value for the author to indicate that the
          # commit was created by a bot.
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          title: Update robots.txt from ai.robots.txt project
          body: |
            See https://github.com/ai-robots-txt/ai.robots.txt
          labels: update-robots-txt
